'use client'

import { createContext, useContext, useEffect, useMemo, useState, ReactNode } from 'react'

export type AppSettings = {
  companyName: string
  slipFooterText: string
  emailSignature: string
  defaultPayrollStart: string
  showConfidential: boolean
  showWatermark: boolean
}

type SettingsContextType = {
  settings: AppSettings
  updateSettings: (payload: Partial<AppSettings>) => void
}

const DEFAULT_SETTINGS: AppSettings = {
  companyName: 'Perisseia',
  slipFooterText: 'Generated by Perisseia',
  emailSignature: 'Finance Division',
  defaultPayrollStart: '1',
  showConfidential: true,
  showWatermark: false,
}

const SettingsContext = createContext<SettingsContextType | null>(null)

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [settings, setSettings] = useState<AppSettings>(DEFAULT_SETTINGS)

  useEffect(() => {
    const stored: AppSettings = {
      companyName: localStorage.getItem('company_name') || DEFAULT_SETTINGS.companyName,
      slipFooterText: localStorage.getItem('slip_footer_text') || DEFAULT_SETTINGS.slipFooterText,
      emailSignature: localStorage.getItem('email_signature') || DEFAULT_SETTINGS.emailSignature,
      defaultPayrollStart: localStorage.getItem('default_payroll_start') || DEFAULT_SETTINGS.defaultPayrollStart,
      showConfidential: localStorage.getItem('slip_confidential_enabled') !== 'false',
      showWatermark: localStorage.getItem('slip_watermark_enabled') === 'true',
    }
    setSettings(stored)
  }, [])

  const updateSettings = (payload: Partial<AppSettings>) => {
    const updated = { ...settings, ...payload }
    setSettings(updated)

    localStorage.setItem('company_name', updated.companyName)
    localStorage.setItem('slip_footer_text', updated.slipFooterText)
    localStorage.setItem('email_signature', updated.emailSignature)
    localStorage.setItem('default_payroll_start', updated.defaultPayrollStart)
    localStorage.setItem('slip_confidential_enabled', String(updated.showConfidential))
    localStorage.setItem('slip_watermark_enabled', String(updated.showWatermark))
  }

  const value = useMemo(() => ({ settings, updateSettings }), [settings])

  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  )
}

export function useSettings() {
  const context = useContext(SettingsContext)
  if (!context) {
    throw new Error('useSettings must be used inside SettingsProvider')
  }
  return context
}