

'use client'

import { useEffect, useState } from 'react'

interface SettingsModalProps {
    open: boolean
    onClose: () => void
}

export default function SettingsModal({ open, onClose }: SettingsModalProps) {

    const [companyName, setCompanyName] = useState('Perisseia')
    const [footerText, setFooterText] = useState('Generated by Perisseia')
    const [emailSignature, setEmailSignature] = useState('Finance Division')
    const [themePrimary, setThemePrimary] = useState('#111111')
    const [themeSurface, setThemeSurface] = useState('#F3EBD9')
    const [themeAccent, setThemeAccent] = useState('#E43427')
    const [themeHighlight, setThemeHighlight] = useState('#15438D')
    const [defaultPayrollStart, setDefaultPayrollStart] = useState('1')
    const [showConfidential, setShowConfidential] = useState(true)
    const [showWatermark, setShowWatermark] = useState(false)

    useEffect(() => {
        if (!open) return

        setCompanyName(localStorage.getItem('company_name') || 'Perisseia')
        setFooterText(localStorage.getItem('slip_footer_text') || 'Generated by Perisseia')
        setEmailSignature(localStorage.getItem('email_signature') || 'Finance Division')
        setThemePrimary(localStorage.getItem('theme_primary') || '#111111')
        setThemeSurface(localStorage.getItem('theme_surface') || '#F3EBD9')
        setThemeAccent(localStorage.getItem('theme_accent') || '#E43427')
        setThemeHighlight(localStorage.getItem('theme_highlight') || '#15438D')
        setDefaultPayrollStart(localStorage.getItem('default_payroll_start') || '1')
        setShowConfidential(localStorage.getItem('show_confidential') !== 'false')
        setShowWatermark(localStorage.getItem('show_watermark') === 'true')

    }, [open])

    function saveSettings() {
        localStorage.setItem('company_name', companyName)
        localStorage.setItem('slip_footer_text', footerText)
        localStorage.setItem('email_signature', emailSignature)
        localStorage.setItem('theme_primary', themePrimary)
        localStorage.setItem('theme_surface', themeSurface)
        localStorage.setItem('theme_accent', themeAccent)
        localStorage.setItem('theme_highlight', themeHighlight)
        localStorage.setItem('default_payroll_start', defaultPayrollStart)
        localStorage.setItem('show_confidential', String(showConfidential))
        localStorage.setItem('show_watermark', String(showWatermark))

        onClose()
    }

    if (!open) return null

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">

            <div className="w-full max-w-2xl bg-[#F3EBD9] border-[6px] border-[#111111] rounded-[40px] shadow-[12px_12px_0px_#111111] overflow-hidden max-h-[90vh] overflow-y-auto">

                {/* HEADER */}
                <div className="sticky top-0 bg-[#E43427] border-b-[6px] border-[#111111] px-8 py-6 flex items-center justify-between z-10">

                    <div>
                        <div className="text-[11px] uppercase tracking-[0.18em] font-black text-[#F3EBD9] opacity-80 mb-2">
                            Global App Configuration
                        </div>

                        <h2 className="text-4xl font-black uppercase tracking-tight text-[#F3EBD9] leading-none">
                            Settings
                        </h2>
                    </div>

                    <button
                        onClick={onClose}
                        className="w-12 h-12 bg-[#111111] text-[#F3EBD9] rounded-2xl border-4 border-[#111111] text-2xl font-black shadow-[4px_4px_0px_#000000] active:translate-y-[2px] active:shadow-[2px_2px_0px_#000000]"
                    >
                        ×
                    </button>
                </div>

                {/* CONTENT */}
                <div className="p-8 flex flex-col gap-8">

                    {/* COMPANY */}
                    <section className="bg-white border-4 border-[#111111] rounded-[32px] p-6 shadow-[6px_6px_0px_#111111]">

                        <div className="text-[11px] uppercase tracking-[0.18em] font-black text-[#15438D] mb-3">
                            Company Identity
                        </div>

                        <div className="grid md:grid-cols-2 gap-5">

                            <div>
                                <div className="text-xs font-black uppercase tracking-[0.12em] mb-2">
                                    Company Name
                                </div>

                                <input
                                    value={companyName}
                                    onChange={(e) => setCompanyName(e.target.value)}
                                    className="w-full bg-[#F3EBD9] border-4 border-[#111111] rounded-2xl px-5 py-4 font-black outline-none"
                                    placeholder="Perisseia"
                                />
                            </div>

                            <div className="md:col-span-2">
                                <div className="text-xs font-black uppercase tracking-[0.12em] mb-4">
                                    Brand Palette
                                </div>

                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

                                    <div
                                        className="border-4 border-[#111111] rounded-3xl p-4 transition-all"
                                        style={{ backgroundColor: `${themePrimary}22` }}
                                    >
                                        <div className="text-[11px] font-black uppercase tracking-widest mb-3">
                                            Primary
                                        </div>

                                        <div className="flex gap-3">
                                            <input
                                                type="color"
                                                value={themePrimary}
                                                onChange={(e) => setThemePrimary(e.target.value)}
                                                className="w-16 h-16 border-4 border-[#111111] rounded-2xl cursor-pointer overflow-hidden bg-white"
                                                style={{ backgroundColor: themePrimary }}
                                            />

                                            <input
                                                value={themePrimary}
                                                onChange={(e) => setThemePrimary(e.target.value)}
                                                className="flex-1 bg-white border-4 border-[#111111] rounded-2xl px-4 py-3 font-black uppercase outline-none"
                                            />
                                        </div>
                                    </div>

                                    <div
                                        className="border-4 border-[#111111] rounded-3xl p-4 transition-all"
                                        style={{ backgroundColor: themeSurface }}
                                    >
                                        <div className="text-[11px] font-black uppercase tracking-widest mb-3">
                                            Surface
                                        </div>

                                        <div className="flex gap-3">
                                            <input
                                                type="color"
                                                value={themeSurface}
                                                onChange={(e) => setThemeSurface(e.target.value)}
                                                className="w-16 h-16 border-4 border-[#111111] rounded-2xl cursor-pointer overflow-hidden bg-white"
                                                style={{ backgroundColor: themeSurface }}
                                            />

                                            <input
                                                value={themeSurface}
                                                onChange={(e) => setThemeSurface(e.target.value)}
                                                className="flex-1 bg-white border-4 border-[#111111] rounded-2xl px-4 py-3 font-black uppercase outline-none"
                                            />
                                        </div>
                                    </div>

                                    <div
                                        className="border-4 border-[#111111] rounded-3xl p-4 transition-all"
                                        style={{ backgroundColor: `${themeAccent}22` }}
                                    >
                                        <div className="text-[11px] font-black uppercase tracking-widest mb-3">
                                            Accent
                                        </div>

                                        <div className="flex gap-3">
                                            <input
                                                type="color"
                                                value={themeAccent}
                                                onChange={(e) => setThemeAccent(e.target.value)}
                                                className="w-16 h-16 border-4 border-[#111111] rounded-2xl cursor-pointer overflow-hidden bg-white"
                                                style={{ backgroundColor: themeAccent }}
                                            />

                                            <input
                                                value={themeAccent}
                                                onChange={(e) => setThemeAccent(e.target.value)}
                                                className="flex-1 bg-white border-4 border-[#111111] rounded-2xl px-4 py-3 font-black uppercase outline-none"
                                            />
                                        </div>
                                    </div>

                                    <div
                                        className="border-4 border-[#111111] rounded-3xl p-4 transition-all"
                                        style={{ backgroundColor: `${themeHighlight}22` }}
                                    >
                                        <div className="text-[11px] font-black uppercase tracking-widest mb-3">
                                            Highlight
                                        </div>

                                        <div className="flex gap-3">
                                            <input
                                                type="color"
                                                value={themeHighlight}
                                                onChange={(e) => setThemeHighlight(e.target.value)}
                                                className="w-16 h-16 border-4 border-[#111111] rounded-2xl cursor-pointer overflow-hidden bg-white"
                                                style={{ backgroundColor: themeHighlight }}
                                            />

                                            <input
                                                value={themeHighlight}
                                                onChange={(e) => setThemeHighlight(e.target.value)}
                                                className="flex-1 bg-white border-4 border-[#111111] rounded-2xl px-4 py-3 font-black uppercase outline-none"
                                            />
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </section>

                    {/* PAYROLL */}
                    <section className="bg-[#15438D] border-4 border-[#111111] rounded-[32px] p-6 shadow-[6px_6px_0px_#111111] text-[#F3EBD9]">

                        <div className="text-[11px] uppercase tracking-[0.18em] font-black opacity-70 mb-3">
                            Payroll Configuration
                        </div>

                        <div className="grid md:grid-cols-2 gap-5">

                            <div>
                                <div className="text-xs font-black uppercase tracking-[0.12em] mb-2">
                                    Default Payroll Start
                                </div>

                                <input
                                    type="number"
                                    value={defaultPayrollStart}
                                    onChange={(e) => setDefaultPayrollStart(e.target.value)}
                                    className="w-full bg-[#F3EBD9] text-[#111111] border-4 border-[#111111] rounded-2xl px-5 py-4 font-black outline-none"
                                />
                            </div>

                            <div>
                                <div className="text-xs font-black uppercase tracking-[0.12em] mb-2">
                                    Email Signature
                                </div>

                                <input
                                    value={emailSignature}
                                    onChange={(e) => setEmailSignature(e.target.value)}
                                    className="w-full bg-[#F3EBD9] text-[#111111] border-4 border-[#111111] rounded-2xl px-5 py-4 font-black outline-none"
                                />
                            </div>
                        </div>
                    </section>

                    {/* SLIP */}
                    <section className="bg-white border-4 border-[#111111] rounded-[32px] p-6 shadow-[6px_6px_0px_#111111]">

                        <div className="text-[11px] uppercase tracking-[0.18em] font-black text-[#E43427] mb-3">
                            Salary Slip
                        </div>

                        <div>
                            <div className="text-xs font-black uppercase tracking-[0.12em] mb-2">
                                Footer Text
                            </div>

                            <textarea
                                value={footerText}
                                onChange={(e) => setFooterText(e.target.value)}
                                rows={3}
                                className="w-full bg-[#F3EBD9] border-4 border-[#111111] rounded-2xl px-5 py-4 font-black outline-none resize-none"
                                placeholder="Generated by Perisseia"
                            />
                        </div>

                        <div className="grid md:grid-cols-2 gap-4 mt-6">

                            <button
                                onClick={() => setShowConfidential(!showConfidential)}
                                className={`border-4 border-[#111111] rounded-2xl px-5 py-4 font-black uppercase tracking-widest transition-all ${showConfidential
                                        ? 'bg-[#111111] text-[#F3EBD9]'
                                        : 'bg-white text-[#111111]'
                                    }`}
                            >
                                {showConfidential ? '✓' : '○'} Confidential
                            </button>

                            <button
                                onClick={() => setShowWatermark(!showWatermark)}
                                className={`border-4 border-[#111111] rounded-2xl px-5 py-4 font-black uppercase tracking-widest transition-all ${showWatermark
                                        ? 'bg-[#15438D] text-[#F3EBD9]'
                                        : 'bg-white text-[#111111]'
                                    }`}
                            >
                                {showWatermark ? '✓' : '○'} Watermark
                            </button>
                        </div>
                    </section>

                </div>

                {/* FOOTER */}
                <div className="sticky bottom-0 bg-[#F3EBD9] border-t-[6px] border-[#111111] px-8 py-6 flex gap-4">

                    <button
                        onClick={onClose}
                        className="flex-1 bg-white border-4 border-[#111111] rounded-2xl py-4 font-black uppercase tracking-widest text-[#111111]"
                    >
                        Cancel
                    </button>

                    <button
                        onClick={saveSettings}
                        className="flex-1 bg-[#E43427] text-[#F3EBD9] border-4 border-[#111111] rounded-2xl py-4 font-black uppercase tracking-widest shadow-[6px_6px_0px_#111111] active:translate-y-[2px] active:shadow-[3px_3px_0px_#111111]"
                    >
                        Save Settings
                    </button>
                </div>

            </div>

        </div>
    )
}